import { CHANNEL_CREATE } from "./CHANNEL_CREATE";
import { GUILD_CREATE } from "./GUILD_CREATE";
import { GUILD_DELETE } from "./GUILD_DELETE";
import { READY } from "./READY";
import { INTERACTION_CREATE } from "./INTERACTION_CREATE";
import { CHANNEL_DELETE } from "./CHANNEL_DELETE";
import { CHANNEL_PINS_UPDATE } from "./CHANNEL_PINS_UPDATE";
import { APPLICATION_COMMAND_PERMISSIONS_UPDATE } from "./APPLICATION_COMMAND_PERMISSIONS_UPDATE";
import { AUTO_MODERATION_ACTION_EXECUTION } from "./AUTO_MODERATION_ACTION_EXECUTION";
import { AUTO_MODERATION_RULE_CREATE } from "./AUTO_MODERATION_RULE_CREATE";
import { AUTO_MODERATION_RULE_DELETE } from "./AUTO_MODERATION_RULE_DELETE";
import { AUTO_MODERATION_RULE_UPDATE } from "./AUTO_MODERATION_RULE_UPDATE";
import { CHANNEL_UPDATE } from "./CHANNEL_UPDATE";
import { GUILD_BAN_ADD } from "./GUILD_BAN_ADD";
import { GUILD_BAN_REMOVE } from "./GUILD_BAN_REMOVE";
import { GUILD_MEMBER_ADD } from "./GUILD_MEMBER_ADD";
import { GUILD_MEMBER_REMOVE } from "./GUILD_MEMBER_REMOVE";
import { GUILD_MEMBER_UPDATE } from "./GUILD_MEMBER_UPDATE";
import { GUILD_MEMBERS_CHUNK } from "./GUILD_MEMBERS_CHUNK";
import { GUILD_ROLE_CREATE } from "./GUILD_ROLE_CREATE";
import { GUILD_ROLE_DELETE } from "./GUILD_ROLE_DELETE";
import { GUILD_ROLE_UPDATE } from "./GUILD_ROLE_UPDATE";
import { GUILD_SCHEDULED_EVENT_CREATE } from "./GUILD_SCHEDULED_EVENT_CREATE";
import { GUILD_SCHEDULED_EVENT_DELETE } from "./GUILD_SCHEDULED_EVENT_DELETE";
import { GUILD_SCHEDULED_EVENT_UPDATE } from "./GUILD_SCHEDULED_EVENT_UPDATE";
import { GUILD_SCHEDULED_EVENT_USER_ADD } from "./GUILD_SCHEDULED_EVENT_USER_ADD";
import { GUILD_SCHEDULED_EVENT_USER_REMOVE } from "./GUILD_SCHEDULED_EVENT_USER_REMOVE";
import { GUILD_STICKERS_UPDATE } from "./GUILD_STICKERS_UPDATE";
import { HELLO } from "./HELLO";
import { INTEGRATION_CREATE } from "./INTEGRATION_CREATE";
import { INTEGRATION_DELETE } from "./INTEGRATION_DELETE";
import { INTEGRATION_UPDATE } from "./INTEGRATION_UPDATE";
import { INVALID_SESSION } from "./INVALID_SESSION";
import { INVITE_CREATE } from "./INVITE_CREATE";
import { INVITE_DELETE } from "./INVITE_DELETE";
import { MESSAGE_CREATE } from "./MESSAGE_CREATE";
import { MESSAGE_DELETE_BULK } from "./MESSAGE_DELETE_BULK";
import { MESSAGE_DELETE } from "./MESSAGE_DELETE";
import { MESSAGE_REACTION_ADD } from "./MESSAGE_REACTION_ADD";
import { MESSAGE_REACTION_REMOVE_ALL } from "./MESSAGE_REACTION_REMOVE_ALL";
import { MESSAGE_REACTION_REMOVE_EMOJI } from "./MESSAGE_REACTION_REMOVE_EMOJI";
import { MESSAGE_REACTION_REMOVE } from "./MESSAGE_REACTION_REMOVE";
import { MESSAGE_UPDATE } from "./MESSAGE_UPDATE";
import { PRESENCE_UPDATE } from "./PRESENCE_UPDATE";
import { RECONNECT } from "./RECONNECT";
import { RESUMED } from "./RESUMED";
import { STAGE_INSTANCE_CREATE } from "./STAGE_INSTANCE_CREATE";
import { STAGE_INSTANCE_DELETE } from "./STAGE_INSTANCE_DELETE";
import { STAGE_INSTANCE_UPDATE } from "./STAGE_INSTANCE_UPDATE";
import { THREAD_CREATE } from "./THREAD_CREATE";
import { THREAD_DELETE } from "./THREAD_DELETE";
import { THREAD_LIST_SYNC } from "./THREAD_LIST_SYNC";
import { THREAD_MEMBER_UPDATE } from "./THREAD_MEMBER_UPDATE";
import { THREAD_MEMBERS_UPDATE } from "./THREAD_MEMBERS_UPDATE";
import { THREAD_UPDATE } from "./THREAD_UPDATE";
import { TYPING_START } from "./TYPING_START";
import { USER_UPDATE } from "./USER_UPDATE";
import { VOICE_SERVER_UPDATE } from "./VOICE_SERVER_UPDATE";
import { VOICE_STATE_UPDATE } from "./VOICE_STATE_UPDATE";
import { WEBHOOKS_UPDATE } from "./WEBHOOKS_UPDATE";
import { GUILD_EMOJIS_UPDATE } from "./GUILD_EMOJIS_UPDATE";

export const handlers = [
  CHANNEL_CREATE,
  GUILD_CREATE,
  GUILD_EMOJIS_UPDATE,
  GUILD_DELETE,
  READY,
  INTERACTION_CREATE,
  CHANNEL_DELETE,
  CHANNEL_PINS_UPDATE,
  APPLICATION_COMMAND_PERMISSIONS_UPDATE,
  AUTO_MODERATION_ACTION_EXECUTION,
  AUTO_MODERATION_RULE_CREATE,
  AUTO_MODERATION_RULE_DELETE,
  AUTO_MODERATION_RULE_UPDATE,
  CHANNEL_UPDATE,
  GUILD_BAN_ADD,
  GUILD_BAN_REMOVE,
  GUILD_MEMBER_ADD,
  GUILD_MEMBER_REMOVE,
  GUILD_MEMBER_UPDATE,
  GUILD_MEMBERS_CHUNK,
  GUILD_ROLE_CREATE,
  GUILD_ROLE_DELETE,
  GUILD_ROLE_UPDATE,
  GUILD_SCHEDULED_EVENT_CREATE,
  GUILD_SCHEDULED_EVENT_DELETE,
  GUILD_SCHEDULED_EVENT_UPDATE,
  GUILD_SCHEDULED_EVENT_USER_ADD,
  GUILD_SCHEDULED_EVENT_USER_REMOVE,
  GUILD_STICKERS_UPDATE,
  HELLO,
  INTEGRATION_CREATE,
  INTEGRATION_DELETE,
  INTEGRATION_UPDATE,
  INVALID_SESSION,
  INVITE_CREATE,
  INVITE_DELETE,
  MESSAGE_CREATE,
  MESSAGE_DELETE_BULK,
  MESSAGE_DELETE,
  MESSAGE_REACTION_ADD,
  MESSAGE_REACTION_REMOVE,
  MESSAGE_REACTION_REMOVE_ALL,
  MESSAGE_REACTION_REMOVE_EMOJI,
  MESSAGE_UPDATE,
  PRESENCE_UPDATE,
  RECONNECT,
  RESUMED,
  STAGE_INSTANCE_CREATE,
  STAGE_INSTANCE_DELETE,
  STAGE_INSTANCE_UPDATE,
  THREAD_CREATE,
  THREAD_DELETE,
  THREAD_LIST_SYNC,
  THREAD_MEMBER_UPDATE,
  THREAD_MEMBERS_UPDATE,
  THREAD_UPDATE,
  TYPING_START,
  USER_UPDATE,
  VOICE_SERVER_UPDATE,
  VOICE_STATE_UPDATE,
  WEBHOOKS_UPDATE,
];
