import { CHANNEL_CREATE } from './CHANNEL_CREATE';
import { GUILD_CREATE } from './GUILD_CREATE';
import { GUILD_DELETE } from './GUILD_DELETE';
import { READY } from './READY';
import { INTERACTION_CREATE } from './INTERACTION_CREATE';
import { CHANNEL_DELETE } from './CHANNEL_DELETE';

export const handlers = [CHANNEL_CREATE, GUILD_CREATE, GUILD_DELETE, READY, INTERACTION_CREATE, CHANNEL_DELETE];
